//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupportEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetail
    {
        public int ClientDetailId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> SoftwareId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual tblSoftware tblSoftware { get; set; }
    }
}
