//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupportEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerSupportEntities : DbContext
    {
        public CustomerSupportEntities()
            : base("name=CustomerSupportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientDetail> ClientDetails { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAssignDeveloper> tblAssignDevelopers { get; set; }
        public virtual DbSet<tblAssignSoftware> tblAssignSoftwares { get; set; }
        public virtual DbSet<tblAssignTicket> tblAssignTickets { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblSoftware> tblSoftwares { get; set; }
        public virtual DbSet<tblSoftwareType> tblSoftwareTypes { get; set; }
        public virtual DbSet<tblTicket> tblTickets { get; set; }
        public virtual DbSet<tblTicketDetail> tblTicketDetails { get; set; }
        public virtual DbSet<tblTicketSolution> tblTicketSolutions { get; set; }
        public virtual DbSet<tblTicketType> tblTicketTypes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
    }
}
