//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupportEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignTicket
    {
        public int AssignTicketId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MessageForMessage { get; set; }
        public Nullable<System.DateTime> AssignmentDeadline { get; set; }
    
        public virtual tblTicket tblTicket { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
