//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupportEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoftware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSoftware()
        {
            this.ClientDetails = new HashSet<ClientDetail>();
            this.tblAssignSoftwares = new HashSet<tblAssignSoftware>();
            this.tblTickets = new HashSet<tblTicket>();
        }
    
        public int SoftwareId { get; set; }
        public string SoftwareName { get; set; }
        public Nullable<int> SoftwareTypeId { get; set; }
        public Nullable<System.DateTime> SoftwareCreatedDate { get; set; }
        public string DeveloperInfo { get; set; }
        public string SoftwareInfo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDetail> ClientDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignSoftware> tblAssignSoftwares { get; set; }
        public virtual tblSoftwareType tblSoftwareType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicket> tblTickets { get; set; }
    }
}
