//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupportEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblAssignDevelopers = new HashSet<tblAssignDeveloper>();
            this.tblAssignSoftwares = new HashSet<tblAssignSoftware>();
            this.tblAssignTickets = new HashSet<tblAssignTicket>();
            this.tblTicketSolutions = new HashSet<tblTicketSolution>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> AuthorizeId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignDeveloper> tblAssignDevelopers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignSoftware> tblAssignSoftwares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignTicket> tblAssignTickets { get; set; }
        public virtual tblDesignation tblDesignation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicketSolution> tblTicketSolutions { get; set; }
        public virtual tblUserType tblUserType { get; set; }
    }
}
